name: "Solar & Energy Monitor"
description: "Unified SolarEdge Modbus TCP, Emporia Vue & CPS Energy Smart Meter Monitor"
version: "1.2.5"
slug: "solar_energy_monitor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 3355
panel_icon: "mdi:chart-timeline-variant-shimmer"
panel_title: "CPS Energy"
ports:
  3355/tcp: 3355
options:
  inverter_ip: "192.168.68.72"
  modbus_port: 502
  poll_interval_ms: 2000
  emporia_user: ""
  emporia_pass: ""
  import_rate_kwh: 0.14
  export_rate_kwh: 0.01
  mqtt_broker: "mqtt://core-mosquitto:1883"
  mqtt_user: "solar"
  mqtt_pass: ""
  cps_user: ""
  cps_pass: ""
  cps_meter_id: ""
schema:
  inverter_ip: str
  modbus_port: int
  poll_interval_ms: int
  emporia_user: str
  emporia_pass: password
  import_rate_kwh: float
  export_rate_kwh: float
  mqtt_broker: str
  mqtt_user: str
  mqtt_pass: password
  cps_user: str
  cps_pass: password
  cps_meter_id: str
